name: Script Linter
on: [push]
jobs:
  Script-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Translation
        uses: actions/checkout@v2
        with:
          path: translation
      - name: Checkout deepLuna
        uses: actions/checkout@v2
        with:
          repository: Hakanaou/deepLuna
          ref: v5.59
          path: deepluna
      - name: Lint
        run: |
          pip3 install -r ${{ github.workspace }}/deepluna/requirements.txt
          ${{ github.workspace }}/deepluna/luna_linter.py --db-path ${{ github.workspace }}/translation/luna_db.json --script-path ${{ github.workspace }}/translation/script/
  Sysmes-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Translation
        uses: actions/checkout@v2
        with:
          path: translation
      - name: Lint
        run: |
          ${{ github.workspace }}/translation/tools/patcher/rebuild_sysmes.py --lint --translation ${{ github.workspace }}/translation/system_strings/sysmes_text.en
